### ISSUE TITLE
Null Simulations for GPF

### ISSUE THREAD

**Issue by dncrwlye** [reptalex/phylofactor#10] opened 2017-12-28 17:20 UTC
that would be sweet!

**Comment by reptalex** [comment] 2018-01-10 01:12
pf.nullsim has been discontinued for the time being to prevent poorly placed trust. A new version will be uploaded which requires users to input functions, randomizeData(pf) and extractOutput(pf) to more explicitly randomize their data given a phylofactor object and define the output they desire from a null simulation.

Stay tuned!

**Comment by reptalex** [comment] 2018-12-17 17:45
Update on null simulations - for the time being, researchers are going to have to design their own null simulations, much like one designs null simulations for multiple regression. Since in some scenarios researchers may want to model collinearity, some latent structure in canonical parameters in null simulations, and a myriad of other effects, the space is too complicated to code up in a `pf.nullsim` function. 

I have some preliminary results on analytical solutions of null distributions of objective functions from phylofactorization, and those will be incorporated to the package as proofs are published, likely in the form of "uncorrected" and "corrected" p-values.

Science!!!

**Closed as completed by reptalex** 2018-12-17 17:45 UTC
